name: Fly Deploy
on: 
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DB_URL: ${{ secrets.DB_URL }}
  GH_CLIENT: ${{ secrets.GH_CLIENT }}
  GH_SECRET: ${{ secrets.GH_SECRET }}
  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy